name: StudyNotion API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies
        working-directory: Server
        run: npm install

      - name: Start backend
        working-directory: Server
        env:
            MONGODB_URL: ${{ secrets.MONGODB_URL }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            FOLDER_NAME: ${{ secrets.FOLDER_NAME }}
            PORT: ${{ secrets.PORT }}
        run: |
            echo "MongoDB URL starts with: ${MONGODB_URL:0:14}"
            npm run dev > backend.log 2>&1 &
            sleep 15
            cat backend.log